# docker-compose.yml

version: '3.9'
services:
    postgres_db:
        image: postgres:14
        container_name: PostgresDB
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=crud_nextjs_app
        volumes:
            - postgres_db:/var/lib/postgresql/data
        ports:
            - '54321:5432'
volumes:
    postgres_db:
        driver: local
